const C=window.APP_CONFIG||{};let sb=null,session=null,settings=null,memberCache=[],yearCache=[];
const months=["জানুয়ারি","ফেব্রুয়ারি","মার্চ","এপ্রিল","মে","জুন","জুলাই","আগস্ট","সেপ্টেম্বর","অক্টোবর","নভেম্বর","ডিসেম্বর"];
const money=n=>new Intl.NumberFormat("bn-BD",{maximumFractionDigits:2}).format(Number(n||0))+" টাকা";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function toast(t){const e=document.querySelector("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)}
function showPage(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(p).classList.add("active");document.querySelectorAll(".navbtn").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="members")loadMembers();if(p==="yearly")loadYears();if(p==="notices")loadNotices();if(p==="admin")loadAdmin()}
document.querySelectorAll(".navbtn").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".adminpane").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById("admin-"+b.dataset.tab).classList.add("active")});
function requireConfig(){if(!C.SUPABASE_URL||C.SUPABASE_URL.includes("YOUR-")){toast("আগে config.js-এ Supabase URL ও anon key বসান");return false}return true}
async function init(){if(!requireConfig())return;sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);const {data:{session:s}}=await sb.auth.getSession();session=s;await refreshUI();sb.auth.onAuthStateChange((_e,s)=>{session=s;refreshUI()})}
async function refreshUI(){const {data}=await sb.from("organization_settings").select("*").eq("id",true).maybeSingle();settings=data||{organization_name:"আল ইহওয়ান ইসলামী সংস্থা বাংলাদেশ",foundation_year:2020,monthly_due:500};document.getElementById("orgName").textContent=settings.organization_name;document.querySelectorAll(".admin-only").forEach(e=>e.classList.toggle("hidden",!session));document.getElementById("loginBtn").textContent=session?"অ্যাডমিন":"অ্যাডমিন লগইন";await loadHome()}
async function loadHome(){const [m,y,n]=await Promise.all([sb.from("public_member_summary").select("*"),sb.from("public_yearly_report").select("*").order("year",{ascending:false}).limit(1),sb.from("public_notices").select("*").limit(3)]);memberCache=m.data||[];yearCache=y.data||[];const r=yearCache[0]||{};document.getElementById("homeCards").innerHTML=[["মোট সদস্য",memberCache.filter(x=>x.status==="active").length],["মোট জমা",money(memberCache.reduce((a,x)=>a+Number(x.total_deposit||0),0))],["মোট লাভ",money(r.total_profit)],["বর্তমান ব্যালেন্স",money(r.balance)]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");renderNotices(n.data||[],"homeNotices")}
async function loadMembers(){const {data,error}=await sb.from("public_member_profit").select("*").order("member_code");if(error){toast(error.message);return}memberCache=data||[];renderMembers()}
function renderMembers(){const q=(document.getElementById("memberSearch").value||"").toLowerCase();document.getElementById("memberRows").innerHTML=memberCache.filter(x=>`${x.member_code} ${x.full_name}`.toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.member_code)}</td><td>${esc(x.full_name)}</td><td>${money(x.total_deposit)}</td><td>${money(x.current_year_style_arrears)}</td><td>${money(x.entitled_profit)}</td></tr>`).join("")||`<tr><td colspan="5">কোনো তথ্য পাওয়া যায়নি</td></tr>`}
document.getElementById("memberSearch").oninput=renderMembers;
async function loadYears(){const {data,error}=await sb.from("public_yearly_report").select("*").order("year",{ascending:true});if(error){toast(error.message);return}yearCache=data||[];const sel=document.getElementById("yearSelect");sel.innerHTML=`<option value="all">সকল বছর</option>`+yearCache.map(x=>`<option value="${x.year}">${x.year}</option>`).join("");sel.onchange=renderYears;renderYears()}
function renderYears(){const val=document.getElementById("yearSelect").value;let rows=yearCache;if(val!=="all")rows=rows.filter(x=>String(x.year)===val);const r=rows.length===1?rows[0]:rows.reduce((a,x)=>({total_members:Math.max(a.total_members||0,x.total_members||0),total_deposit:(a.total_deposit||0)+Number(x.total_deposit||0),total_arrears:Number(x.total_arrears||0),total_investment:(a.total_investment||0)+Number(x.total_investment||0),total_profit:(a.total_profit||0)+Number(x.total_profit||0),total_expense:(a.total_expense||0)+Number(x.total_expense||0),balance:(a.balance||0)+Number(x.balance||0)}),{});document.getElementById("yearCards").innerHTML=[["মোট সদস্য",r.total_members||0],["মোট জমা",money(r.total_deposit)],["মোট বকেয়া",money(r.total_arrears)],["মোট বিনিয়োগ",money(r.total_investment)],["মোট লাভ",money(r.total_profit)],["মোট খরচ",money(r.total_expense)],["অবশিষ্ট ব্যালেন্স",money(r.balance)]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");document.getElementById("yearRows").innerHTML=yearCache.map(x=>`<tr><td>${x.year}</td><td>${x.total_members}</td><td>${money(x.total_deposit)}</td><td>${money(x.total_arrears)}</td><td>${money(x.total_investment)}</td><td>${money(x.total_profit)}</td><td>${money(x.total_expense)}</td><td>${money(x.balance)}</td></tr>`).join("")}
async function loadNotices(){const {data,error}=await sb.from("public_notices").select("*").order("published_at",{ascending:false});if(error){toast(error.message);return}renderNotices(data||[],"noticeList")}
function renderNotices(data,id){document.getElementById(id).innerHTML=data.length?data.map(n=>`<article class="notice"><h3>${esc(n.title)}</h3><time>${new Date(n.published_at||n.created_at).toLocaleDateString("bn-BD")}</time><p>${esc(n.body)}</p></article>`).join(""):`<div class="panel">কোনো প্রকাশিত নোটিশ নেই।</div>`}
async function loadAdmin(){if(!session)return;const {data}=await sb.from("members").select("id,member_code,full_name").order("member_code");const sel=document.getElementById("paymentMember");sel.innerHTML=(data||[]).map(x=>`<option value="${x.id}">${esc(x.member_code)} — ${esc(x.full_name)}</option>`).join("");document.querySelector('[name="payment_year"]').value=new Date().getFullYear();document.querySelector('[name="entry_year"]').value=new Date().getFullYear();document.querySelector('[name="entry_date"]').value=new Date().toISOString().slice(0,10);document.querySelector('[name="organization_name"]').value=settings.organization_name;document.querySelector('[name="foundation_year"]').value=settings.foundation_year;document.querySelector('[name="monthly_due"]').value=settings.monthly_due;document.querySelector('[name="payment_month"]').innerHTML=months.map((m,i)=>`<option value="${i+1}">${m}</option>`).join("")}
document.getElementById("loginBtn").onclick=()=>{if(session)showPage("admin");else document.getElementById("modal").classList.remove("hidden")};
document.getElementById("closeModal").onclick=()=>document.getElementById("modal").classList.add("hidden");
document.getElementById("loginForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(error)toast(error.message);else{document.getElementById("modal").classList.add("hidden");showPage("admin")}};
document.getElementById("logoutBtn").onclick=async()=>{await sb.auth.signOut();showPage("home")};
document.getElementById("memberForm").onsubmit=async e=>{e.preventDefault();if(!session)return;const f=new FormData(e.target);const {error}=await sb.from("members").insert({member_code:f.get("member_code"),full_name:f.get("full_name"),phone:f.get("phone")||null,join_date:f.get("join_date")||null,status:f.get("status"),notes:f.get("notes")||null});if(error)toast(error.message);else{toast("সদস্য সংরক্ষিত হয়েছে");e.target.reset();loadAdmin();loadHome()}};
document.getElementById("paymentForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from("member_payments").upsert({member_id:f.get("member_id"),payment_year:Number(f.get("payment_year")),payment_month:Number(f.get("payment_month")),amount:Number(f.get("amount")),paid_at:f.get("paid_at")||null,note:f.get("note")||null},{onConflict:"member_id,payment_year,payment_month"});if(error)toast(error.message);else{toast("মাসিক জমা সংরক্ষিত হয়েছে");e.target.reset();loadHome()}};
document.getElementById("financeForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from("financial_entries").insert({entry_year:Number(f.get("entry_year")),entry_date:f.get("entry_date"),entry_type:f.get("entry_type"),amount:Number(f.get("amount")),description:f.get("description")||null});if(error)toast(error.message);else{toast("আর্থিক তথ্য সংরক্ষিত হয়েছে");e.target.reset();loadHome()}};
document.getElementById("noticeForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from("notices").insert({title:f.get("title"),body:f.get("body"),published:true});if(error)toast(error.message);else{toast("নোটিশ প্রকাশিত হয়েছে");e.target.reset();loadNotices();loadHome()}};
document.getElementById("settingsForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.from("organization_settings").update({organization_name:f.get("organization_name"),foundation_year:Number(f.get("foundation_year")),monthly_due:Number(f.get("monthly_due")),updated_at:new Date().toISOString()}).eq("id",true);if(error)toast(error.message);else{toast("সেটিংস আপডেট হয়েছে");await refreshUI();loadAdmin()}};
init();