-- আল ইহওয়ান ইসলামী সংস্থা বাংলাদেশ
create table if not exists members (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  father_name text,
  mobile text,
  join_date date,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now()
);
create table if not exists payments (
  id bigint generated by default as identity primary key,
  member_id uuid not null references members(id) on delete cascade,
  year integer not null,
  month integer not null check(month between 1 and 12),
  required_amount numeric(12,2) not null default 500,
  paid_amount numeric(12,2) not null default 0,
  payment_date date,
  created_at timestamptz not null default now(),
  unique(member_id, year, month)
);
create table if not exists profits (
  id bigint generated by default as identity primary key,
  year integer not null unique,
  total_profit numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  year integer not null,
  date date not null,
  description text not null,
  amount numeric(14,2) not null,
  created_at timestamptz not null default now()
);
create table if not exists investments (
  id bigint generated by default as identity primary key,
  year integer not null,
  date date not null,
  description text not null,
  amount numeric(14,2) not null,
  created_at timestamptz not null default now()
);
create table if not exists notices (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  publish_date date not null default current_date,
  status text not null default 'published' check(status in ('published','draft')),
  created_at timestamptz not null default now()
);
create table if not exists settings (
  id boolean primary key default true,
  organization_name text not null default 'আল ইহওয়ান ইসলামী সংস্থা বাংলাদেশ',
  monthly_contribution numeric(10,2) not null default 500,
  start_year integer
);
insert into settings(id) values(true) on conflict (id) do nothing;

-- Public read policies: production setup should restrict fields/views as needed.
alter table members enable row level security;
alter table payments enable row level security;
alter table profits enable row level security;
alter table expenses enable row level security;
alter table investments enable row level security;
alter table notices enable row level security;
alter table settings enable row level security;

create policy "public read active members" on members for select using (status='active');
create policy "public read payments" on payments for select using (true);
create policy "public read profits" on profits for select using (true);
create policy "public read expenses" on expenses for select using (true);
create policy "public read investments" on investments for select using (true);
create policy "public read notices" on notices for select using (status='published');
create policy "public read settings" on settings for select using (true);
