-- আল ইখওয়ান ইসলামী সংস্থা বাংলাদেশ
-- হিসাব শুরুর বছর: ২০২১ | প্রতিষ্ঠা: ২০২০

create table if not exists members (
  id uuid primary key default gen_random_uuid(), name text not null, father_name text, mobile text, join_date date,
  status text not null default 'active' check (status in ('active','inactive')), created_at timestamptz not null default now()
);
create table if not exists payments (
  id bigint generated by default as identity primary key, member_id uuid not null references members(id) on delete cascade,
  year integer not null, month integer not null check(month between 1 and 12), required_amount numeric(12,2) not null default 500,
  paid_amount numeric(12,2) not null default 0, payment_date date, created_at timestamptz not null default now(), unique(member_id, year, month)
);
create table if not exists profits (
  id bigint generated by default as identity primary key, year integer not null unique, total_profit numeric(14,2) not null default 0, created_at timestamptz not null default now()
);
create table if not exists expenses (
  id bigint generated by default as identity primary key, year integer not null, date date not null, description text not null, amount numeric(14,2) not null, created_at timestamptz not null default now()
);
create table if not exists investments (
  id bigint generated by default as identity primary key, year integer not null, date date not null, description text not null, amount numeric(14,2) not null, created_at timestamptz not null default now()
);
create table if not exists member_settlements (
  id bigint generated by default as identity primary key, member_id uuid not null references members(id), settlement_date date not null default current_date, amount_paid numeric(14,2) not null, note text, created_at timestamptz not null default now()
);
-- অবশিষ্ট অর্থ কোন খাতে আছে: পণ্য, জমি, অন্যান্য সম্পদ ইত্যাদি। amount হলো fund থেকে বের হওয়া/সম্পদে রাখা টাকা।
create table if not exists assets (
  id bigint generated by default as identity primary key, year integer not null, date date not null default current_date,
  category text not null, description text not null, amount numeric(14,2) not null, status text not null default 'active' check(status in ('active','sold','returned')),
  created_at timestamptz not null default now()
);

create index if not exists assets_year_idx on assets(year);
create index if not exists assets_category_idx on assets(category);

create table if not exists notices (
  id bigint generated by default as identity primary key, title text not null, description text not null, publish_date date not null default current_date,
  status text not null default 'published' check(status in ('published','draft')), created_at timestamptz not null default now()
);
create table if not exists settings (
  id boolean primary key default true, organization_name text not null default 'আল ইখওয়ান ইসলামী সংস্থা বাংলাদেশ', monthly_contribution numeric(10,2) not null default 500, start_year integer not null default 2021
);
insert into settings(id,organization_name,monthly_contribution,start_year) values(true,'আল ইখওয়ান ইসলামী সংস্থা বাংলাদেশ',500,2021) on conflict(id) do update set organization_name=excluded.organization_name, monthly_contribution=excluded.monthly_contribution, start_year=excluded.start_year;

-- RLS
alter table members enable row level security; alter table payments enable row level security; alter table profits enable row level security; alter table expenses enable row level security; alter table investments enable row level security; alter table member_settlements enable row level security; alter table assets enable row level security; alter table notices enable row level security; alter table settings enable row level security;

create or replace function public.is_admin() returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.role='admin'); $$;

-- Existing policies may exist from previous runs. Drop only these names, then recreate safely.
drop policy if exists "public read active members" on members; drop policy if exists "public read payments" on payments; drop policy if exists "public read profits" on profits; drop policy if exists "public read expenses" on expenses; drop policy if exists "public read investments" on investments; drop policy if exists "public read notices" on notices; drop policy if exists "public read settings" on settings;
drop policy if exists "public read assets" on assets;
drop policy if exists "admin members all" on members; drop policy if exists "admin payments all" on payments; drop policy if exists "admin profits all" on profits; drop policy if exists "admin expenses all" on expenses; drop policy if exists "admin investments all" on investments; drop policy if exists "admin settlements all" on member_settlements; drop policy if exists "admin assets all" on assets; drop policy if exists "admin notices all" on notices; drop policy if exists "admin settings all" on settings;

create policy "public read active members" on members for select using(status='active');
create policy "public read payments" on payments for select using(true);
create policy "public read notices" on notices for select using(status='published');
create policy "public read settings" on settings for select using(true);
create policy "public read assets" on assets for select using(status='active');

-- Profit, expense, investment, settlement details remain admin-only.
create policy "admin members all" on members for all using(public.is_admin()) with check(public.is_admin());
create policy "admin payments all" on payments for all using(public.is_admin()) with check(public.is_admin());
create policy "admin profits all" on profits for all using(public.is_admin()) with check(public.is_admin());
create policy "admin expenses all" on expenses for all using(public.is_admin()) with check(public.is_admin());
create policy "admin investments all" on investments for all using(public.is_admin()) with check(public.is_admin());
create policy "admin settlements all" on member_settlements for all using(public.is_admin()) with check(public.is_admin());
create policy "admin assets all" on assets for all using(public.is_admin()) with check(public.is_admin());
create policy "admin notices all" on notices for all using(public.is_admin()) with check(public.is_admin());
create policy "admin settings all" on settings for all using(public.is_admin()) with check(public.is_admin());

-- Public safe summary: member profit is deliberately excluded.
create or replace view public.member_public_summary as
select m.id,m.name,m.status,coalesce(sum(p.paid_amount),0) total_deposit,coalesce(sum(greatest(p.required_amount-p.paid_amount,0)),0) due
from members m left join payments p on p.member_id=m.id where m.status='active' group by m.id,m.name,m.status;

-- CURRENT FUND RULE
-- total member deposits + recorded profit-after-expenses - active asset allocations - member settlements.
-- Important: total_profit must be the net profit AFTER expenses, so expenses are not subtracted again here.
-- Assets include land, products given/purchased for someone, investments, or other amounts moved out of cash fund.
create or replace view public.current_fund_summary as
select
  coalesce((select sum(paid_amount) from payments),0) +
  coalesce((select sum(total_profit) from profits),0) -
  coalesce((select sum(amount) from assets where status='active'),0) -
  coalesce((select sum(amount_paid) from member_settlements),0) as current_fund;

create or replace view public.annual_summary as
select y.year, coalesce((select sum(paid_amount) from payments p where p.year=y.year),0) total_deposit,
coalesce((select total_profit from profits pr where pr.year=y.year),0) total_profit,
coalesce((select sum(amount) from expenses e where e.year=y.year),0) total_expense,
coalesce((select sum(amount) from investments i where i.year=y.year),0) total_investment,
coalesce((select sum(amount) from assets a where a.year=y.year and a.status='active'),0) asset_amount
from generate_series(2021, extract(year from current_date)::int) y(year);

grant select on public.member_public_summary, public.current_fund_summary, public.annual_summary to anon, authenticated;
grant select on public.members, public.payments, public.assets, public.notices, public.settings to anon, authenticated;
